config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  resources :lists do
    resources :bookmarks, only: %i[new create]
    resources :reviews, only: %i[create]
  end
  resources :bookmarks, only: %i[edit update destroy] do
    member do
      get :details
    end
  end
  resources :reviews, only: %i[edit update destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :movie_id, :list_id, presence: true
  validates :movie_id, uniqueness: { scope: :list_id }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many :reviews, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list

  validates :author, :comment, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]
  before_action :set_bookmark, only: %i[edit update destroy details]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      respond_to do |format|
        format.html { redirect_to list_path(@list) }
        format.turbo_stream do
          render turbo_stream: turbo_stream.append('movie-cards', partial: 'bookmarks/bookmark', locals: { bookmark: @bookmark })
        end
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    list = @bookmark.list
    @bookmark.destroy
    redirect_to list_path(list)
  end

  def details; end

  def edit; end

  def update
    if @bookmark.update(bookmark_params)
      respond_to do |format|
        format.html { redirect_to @bookmark.list }
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace('modal', template: 'bookmarks/details')
        end
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment, :personal_rating)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show edit update destroy]

  def index
    @lists = List.all
    @list = List.new
  end

  def show
    @reviews = @list.reviews
    @review = Review.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      respond_to do |format|
        format.html { redirect_to @list }
        format.turbo_stream { render turbo_stream: turbo_stream.append('watchlists', partial: 'lists/list', locals: { list: @list }) }
      end
    else
      render :new, status: :unprocessable_entity # assures the modal doesn't close after submit
    end
  end

  def edit; end

  def update
    if @list.update(list_params)
      respond_to do |format|
        format.html { redirect_to @list }
        format.turbo_stream do
          render turbo_stream: turbo_stream.update('listname', @list.name)
        end
      end
    else
      render :new, status: :unprocessable_entity # assures the modal doesn't close after submit
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_list, only: %i[create]
  def create
    @review = Review.new(review_params)
    @review.list = @list
    if @review.save
      redirect_to @list
    else
      render 'lists/show'
    end
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def review_params
    params.require(:review).permit(:author, :comment, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/_bookmark.html.erb
<% movie = bookmark.movie %>
<%= link_to details_bookmark_path(bookmark), data: { turbo: true, turbo_frame: "modal" }  do %>
  <div class="card-movie" style="background-image: url(<%= movie.poster_url%>)">
    <p class="card-rating"><i class="far fa-star"></i> <%= movie.rating %></p>
  </div>
<% end %>

app/views/bookmarks/details.html.erb
<% movie = @bookmark.movie %>

<%= render "shared/modal", modal_width: "modal-lg-width card-details" do %>
  <div class="row">
    <%# Poster %>
    <div class="col-12 col-sm-4">
      <img src="<%= movie.poster_url %>" alt="<%= movie.title %> poster">
    </div>
    <%# Info %>
    <div class="col-12 col-sm-8">
      <h1 class="m-0"><%= movie.title %></h1>
      <small>Rating: <%= movie.rating %> | <%= link_to "Remove from list", bookmark_path(@bookmark), method: :delete, class: "link-underline link-gold", data: { confirm: "Are you sure you want to remove this movie from your list?" } %></small>
      <h4 class="mt-4 mb-0">Overview:</h4>
      <p><%= movie.overview %></p>
      <div class="d-flex align-items-center mt-4">
        <h4 class="mb-0">Comment:</h4>
        <%= link_to edit_bookmark_path(@bookmark), data: { turbo: true, turbo_frame: 'comment' } do %>
          <i class="fas fa-edit ms-3"></i>
        <% end %>
      </div>
      <%= turbo_frame_tag 'comment' do %>
        <p><%= @bookmark&.comment %></p>
      <% end %>
    </div>
  </div>
<% end %>

app/views/bookmarks/edit.html.erb
<%= turbo_frame_tag "comment" do %>
  <%= simple_form_for @bookmark, html: { class: "mt-3", data: { turbo: true, turbo_frame: 'comment' } } do |f| %>
    <%= f.input :comment,
                as: :text,
                label: false,
                placeholder: "Comment",
                autofocus: true,
                wrapper_html: {class: "inplace-form"} %>
    <%= f.submit class: "btn-capsule-sm btn-outline-gold mt-3" %>
  <% end %>
<% end %>

app/views/bookmarks/new.html.erb
<%= render "shared/modal", modal_width: "modal-md-width" do %>
  <h3 class="modal-title">Add movies</h3>
  <%= simple_form_for [@list, @bookmark], html: { class: "mt-3", data: { turbo: true } } do |f| %>
    <%= f.association :movie,
                      label: false,
                      prompt: 'Movie',
                      collection: Movie.all.order(:title),
                      wrapper_html: { class: "form-list" } %>
    <%= f.input :comment,
                as: :text,
                label: false,
                placeholder: 'Comment',
                wrapper_html: {class: "form-list"} %>
    <div class="text-center">
      <%= f.submit class: "btn-capsule-sm btn-outline-gold mt-2" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="page-content">
      <%= yield %>
    </div>
    <%= render "shared/footer" unless current_page?(root_url) %>
    <%= turbo_frame_tag "modal" %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for list, html: { class: "mt-3 text-center", data: { turbo: true } } do |f| %>
  <%= f.input :name, label: false, placeholder: "Enter the name of your new list",  wrapper_html: {class: "form-list"} %>
  <%= f.submit class: "btn-capsule-sm btn-outline-gold mt-2" %>
<% end %>

app/views/lists/_list.html.erb
<%= link_to list do %>
  <div style="background-image: url('<%= image_url 'movies.jpg'%>')", class="card-list">
    <div class="card-list-info">
      <h5><%= list.name %></h5>
      <p><%= list.movies.empty? ? 0 : list.movies.length  %> movies</p>
    </div>
  </div>
<% end %>

app/views/lists/edit.html.erb
<%= render "shared/modal", modal_width: "modal-md-width" do %>
  <h3 class="modal-title">Edit list</h3>
  <%= render "form", list: @list %>
<% end %>

app/views/lists/index.html.erb
<div class="banner banner-section" style="background-image: linear-gradient(0deg, rgba(0,0,0,0.8) 25%, rgba(0,0,0,0.9) 100%), url('<%= image_url 'lists.jpg'%>')">
  <div class="banner-content">
    <div class="banner-container">
      <h1>Watch Lists</h1>
    </div>
  </div>
</div>
<div class="container p-5 text-center">
  <%= link_to new_list_path, class: "btn-capsule btn-gold", data: { turbo: true, turbo_frame: "modal" } do %>
    <i class="fas fa-plus me-2"></i>New List
  <% end %>
  <div class="cards mt-3" id="watchlists">
    <% @lists.each do |list| %>
      <%= render "list", list: list %>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<%= render "shared/modal", modal_width: "modal-md-width" do %>
  <h3 class="modal-title">Add a new list</h3>
  <%= render "form", list: @list %>
<% end %>

app/views/lists/show.html.erb
<div class="banner banner-section" style="background-image: linear-gradient(0deg, rgba(0,0,0,0.75) 25%, rgba(0,0,0,0.7) 100%), url('<%= image_url 'movies.jpg'%>')">
  <div class="banner-content">
    <div class="banner-container p-2 p-md-3">
      <h1 id="listname"><%= @list.name %></h1>
      <%= link_to edit_list_path(@list), class: "mx-3", data: { turbo: true, turbo_frame: "modal" } do %>
        <div class="btn-capsule-sm btn-frosted">
          <i class="fas fa-pen me-2"></i> Edit
        </div>
      <% end %>
      <%= link_to list_path(@list), method: :delete, class: "mx-3", data: { confirm: "Are you sure you want to delete this watchlist?" } do %>
        <div class="btn-capsule-sm btn-frosted">
          <i class="far fa-trash-alt me-2"></i> Delete
        </div>
      <% end %>
    </div>
  </div>
</div>
<div class="container p-1 p-sm-3 text-center">
  <%= link_to new_list_bookmark_path(list_id: @list), class: "btn-capsule btn-gold my-3", data: { turbo: true, turbo_frame: 'modal' } do %>
    <i class="fas fa-plus me-2"></i>Add a movie
  <% end %>
  <div class="cards p-1 p-sm-3" id="movie-cards">
    <% @list.bookmarks&.each do |bookmark| %>
      <%= render "bookmarks/bookmark", bookmark: bookmark %>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner banner-full" style="background-image: linear-gradient(0deg, rgba(0,0,0,0.75) 25%, rgba(0,0,0,0.7) 100%), url('<%= image_url "home.jpg"%>')">
  <div class="banner-container">
    <h1>This is a watch list app!</h1>
    <p>Create your own movie lists</p>
  </div>
  <%= link_to "See all lists", lists_path, class: "btn-capsule btn-frosted mt-2" %>
</div>

app/views/reviews/_form.html.erb
<div>
  <%= simple_form_for [list, review] do |f| %>
    <%= f.input :author %>
    <%= f.input :comment %>
    <%= f.input :rating %>
    <%= f.submit %>
  <% end %>
</div>

app/views/reviews/_review.html.erb
<div class="card-review">
  <h5><%= review.rating %></h5>
  <span><%= review.author %></span> - <small><%= (Time.now - review.created_at) / 60 %> minutes ago</small>
  <p><%= review.comment %></p>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="links">
    <%= link_to "https://github.com/pmkihara" do %>
      <i class="fab fa-github"></i>
    <% end %>
    <%= link_to "https://www.linkedin.com/in/patricia-kihara" do %>
      <i class="fab fa-linkedin-in ms-3"></i>
    <% end %>
  </div>
  <div>
    <p>Patricia Mey Kihara - Le Wagon #690</p>
  </div>
</div>

app/views/shared/_modal.html.erb
<%# Modal base for using with Turbo Hotwire %>
<%# OBS: When rendering, it must receive as arguments:<modal width class> %>
  <%= turbo_frame_tag "modal" do %>
  <div id="editTitleModal" data-controller="turbo-modal" data-turbo="true">
    <div class="transparent-overlay dark-transparent-background" data-action="click->turbo-modal#closeModal"></div>
    <%= turbo_frame_tag "modal-body" do %>
      <div class="modal-card <%= modal_width %>">
        <i class="fas fa-times modal-close-button" data-action= "click->turbo-modal#closeModal" data-modal-layer= 'editTitleModal'></i>
        <%= yield %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="links">
    <%= link_to root_path, class: "links" do %>
      <div class="logo me-3">
        <%= inline_svg_tag "popcorn.svg" %>
      </div>
    <% end %>
  </div>
  <div class="links">
    <%= link_to "All Lists", lists_path, class: "ms-3" %>
  </div>
</div>